planning:
  epsilon: 100
  verbose: false
  verbose_collisions: false
  shortcut_path: false
  interpolate_path: false
  use_bfs_heuristic: true
  group_name: arm2
  planning_joints:
   arm2_shoulder_pan_joint
   arm2_shoulder_lift_joint
   arm2_upper_arm_roll_joint
   arm2_elbow_flex_joint
   arm2_forearm_roll_joint
   arm2_wrist_flex_joint
   arm2_wrist_roll_joint
  discretization: 360 360 360 360 360 360 360

debug:
  print_out_path: false
  logging:
    expands: info
    expands2: info
    ik: info
    robot_model: info
    collisions: info
    solution: info

visualizations:
  heuristic: false
  goal: true
  expanded_states: true
  trajectory: false
  collision_model_trajectory: false
  trajectory_throttle: 30

